### ISSUE TITLE
add crown mice collection with integration to @tehhowch

### ISSUE THREAD

**Issue by DevJackSmith** [DevJackSmith/mh-helper-extension#2]
@tehhowch
for format see: http://horntracker.com/backend/mostmice.php?function=hunters&hunters=<fbuid\>

* request is comma separated list of uids
* needs request (post and get) end point
* needs to not impact bandwidth and cpu much
* currently runs every hour
* currently about 3800 uids
* currently about 850 mice
---
* need to update readme on extension for this
* need to make this an opt-in option (off by default)
* need to make this read user profile as well as other users profile
---
* db side make a new db with tables for each:
  * uids - autogenerated user_id - last updated timestamp
  * user_id - mouse_id - mouse_count
  * mouse_id - mouse_name
---
Idea A: add timestamp to each uid and only respond with the ones that got updated since time in the request
Idea B: send the info straight from extension to tehhowch
Open to other ideas

**Comment by tehhowch** [comment]
- Supporting GET requests is simplest, as I already use GET requests with HornTracker. 
   - Supplying a POST endpoint would allow us to limit the response size you need to send by a per-user timestamp (preferably utc millis since the epoch) comparison.
   - We could opt for a URL encoding too, e.g. `&since=<utc_millis>` (this would slightly decrease the per-request batch size from 127)
 - I can import raw JSON, gzip, or zip data formats without hassle.

Currently the data archive job runs at ~hh:12 to ~hh:16, and generally is able to get through about 600 - 1800 ids (based on how timely HT is with its responses) per session. After all the ids are checked for new data, the next hour will be an off-hour (as the job is then to print the scoreboard instead of get new data).

**Comment by DevJackSmith** [comment]
a bit stuck on how google expects me to update it from browser... seems they only allow service accounts and oauth2. Which means I have to send it from browser extension to a server first, and only then to goole/fusion table.

**Comment by tehhowch** [comment]
A Google Apps Script project can be deployed as a webapp (like I did with snow golem loot) and receive get/post requests. That Apps Script webapp could then handle the upload to your FusionTable. Depending on options in the initial request, it could do other things too, like serve the data as json (to those who don't want to figure out how to interact with the fusion table,v or don't have the needed permissions to do so, etc)

**Comment by DevJackSmith** [comment]
published in v1.12.26. Please let me know how I can help integrate it now to your tools.

**Comment by DevJackSmith** [comment]
@tehhowch how is this going on your end? anything I can help with? (want to finish this one).

**Comment by tehhowch** [comment]
Pushed to prod today, so MHCC members who use your extension instead of HornTracker will now have their crown snapshots successfully imported.
Refs https://github.com/tehhowch/apps-script/pull/13, https://github.com/tehhowch/apps-script/issues/12
