### ISSUE TITLE
PLEASE DO NOT ADD ISSUES HERE, ADD THEM IN mh-hunt-helper repo

### ISSUE THREAD

**Issue by DevJackSmith** [DevJackSmith/mh-helper-extension#7]
Link: https://github.com/DevJackSmith/mh-hunt-helper/issues
Thinking we can keep all the issues there for easy searching.

**Comment by tsitu** [comment]
Just wanted to double check to make sure it's OK to close this issue.

I was also thinking about transferring existing issues over from `mh-hunt-helper` and adding more specific labels to them.

**Comment by DevJackSmith** [comment]
The reason why i did this is because our users (non-technical) won't be looking through multiple places to see if their request is already filed. A lot of people don't check if a bug is already filed, and much less in multiple places. I'm ok with it if you guys think this is necessary, what are the benefits? you can create more specific labels in the other repo too.

**Comment by tsitu** [comment]
On the off chance that a non-technical user decides to browse through filed issues, I think having a clear separation of concerns between website and extension might actually help. Separating them will contain each issue list to a single consistent page, which means the user won't have to figure out how to add a `label:extension` filter or navigate between 2+ pages.

It'll also simplify linking to issues from PRs and vice versa, especially since virtually all of our contributions are on this repo at the moment.

**Comment by DevJackSmith** [comment]
there's no right/wrong way. So closing this issue to proceed with separation.
